<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Include="..\CommonAssemblyInfo.cs">
      <Link>Properties\CommonAssemblyInfo.cs</Link>
    </Compile>
    <Compile Include="..\GitTfs.VsCommon\ParentForm.cs">
      <Link>ParentForm.cs</Link>
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="..\GitTfs.VsCommon\Retry.cs">
      <Link>Retry.cs</Link>
    </Compile>
    <Compile Include="..\GitTfs.VsCommon\TfsHelper.Common.cs">
      <Link>TfsHelper.Common.cs</Link>
    </Compile>
    <Compile Include="..\GitTfs.VsCommon\TfsHelper.VS2017Base.cs">
      <Link>TfsHelper.VS2017Base.cs</Link>
    </Compile>
    <Compile Include="..\GitTfs.VsCommon\TfsPlugin.cs">
      <Link>TfsPlugin.cs</Link>
    </Compile>
    <Compile Include="..\GitTfs.VsCommon\Wrappers.cs">
      <Link>Wrappers.cs</Link>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\GitTfs\GitTfs.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.TeamFoundationServer.ExtendedClient" Version="20.256.2" />
    <PackageReference Include="Microsoft.VisualStudio.Settings.15.0" Version="17.10.34916.79" />
    <PackageReference Include="Microsoft.VisualStudio.Setup.Configuration.Interop" Version="3.14.2075" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy /y /I &quot;$(TargetDir)*.dll&quot; &quot;$(SolutionDir)GitTfs\$(OutDir)$(ProjectName)&quot; /EXCLUDE:..\build\files_to_ignore_during_post_build_copy.txt" />
    <Exec Command="xcopy /y /I &quot;$(TargetDir)*.pdb&quot; &quot;$(SolutionDir)GitTfs\$(OutDir)$(ProjectName)&quot; /EXCLUDE:..\build\files_to_ignore_during_post_build_copy.txt" />
  </Target>
</Project>